import {Game,PADS,TYPES,ENEMIES,WAVES,towerStats,upgradeCost,sellValue} from './engine.js';
import {render,drawTowerIcon} from './render.js';
import {Soundscape} from './sound.js';
const $=id=>document.getElementById(id), game=new Game(), music=new Soundscape();
const ctx=$('board').getContext('2d');
let selectedTower=null,buildType=null,hoverPad=null,last=performance.now(),lastUI=0,oldStatus=game.status,oldWave=0,wasPaused=false;
const reducedMotion=matchMedia('(prefers-reduced-motion: reduce)').matches;
function notify(text){$('toast').textContent=text;}
function chooseType(type){selectedTower=null;buildType=buildType===type?null:type;notify(buildType?`已選 ${TYPES[type].name}，點地圖上的 ＋ 建造。Esc 可取消。`:'已取消選塔。');sync();}
function selectPad(id){if(game.status==='won'||game.status==='lost')return;const tower=game.towers.find(t=>t.padId===id);if(tower){selectedTower=tower.id;buildType=null;notify(`已選 ${TYPES[tower.type].name} · 據點 ${id.slice(1)}`);}else if(buildType){const result=game.build(buildType,id);if(result.ok){selectedTower=result.towerId;buildType=null;music.cue('build');notify('守護塔已點亮。可升級，或再選另一座塔。');}else notify(result.reason);}else{selectedTower=null;notify(`據點 ${id.slice(1)} 尚未建造。先選工坊中的守護塔。`);}sync();}
for(const [type,spec] of Object.entries(TYPES)){const button=document.createElement('button');button.className='tower-card';button.dataset.type=type;button.setAttribute('aria-label',`選擇${spec.name}，${spec.cost}文，${spec.role}`);button.innerHTML=`<canvas width="84" height="92" aria-hidden="true"></canvas><span><strong>${spec.name}</strong><small>${spec.role}</small></span><span class="tower-price">${spec.cost}<small>文</small></span>`;button.addEventListener('click',()=>chooseType(type));$('tower-shop').append(button);drawTowerIcon(button.querySelector('canvas').getContext('2d'),type,42,49,61,1);}
for(const pad of PADS){const button=document.createElement('button');button.className='pad-control';button.style.left=`${pad.x/960*100}%`;button.style.top=`${pad.y/600*100}%`;button.dataset.pad=pad.id;button.setAttribute('aria-label',`據點 ${pad.id.slice(1)}，空地`);button.title=`據點 ${pad.id.slice(1)}`;button.textContent=pad.id.slice(1);button.addEventListener('click',()=>selectPad(pad.id));button.addEventListener('pointerenter',()=>{hoverPad=pad.id;});button.addEventListener('pointerleave',()=>{hoverPad=null;});button.addEventListener('focus',()=>{hoverPad=pad.id;});button.addEventListener('blur',()=>{hoverPad=null;});$('pad-buttons').append(button);}
$('board').addEventListener('click',()=>{selectedTower=null;buildType=null;notify('已取消選取。');sync();});
function upgrade(){const tower=game.towers.find(t=>t.id===selectedTower);if(!tower)return;const result=game.upgrade(tower.id);notify(result.ok?`${TYPES[tower.type].name} 已升至 ${tower.level} 級。`:result.reason);if(result.ok)music.cue('upgrade');sync();}
function sell(){const result=game.sell(selectedTower);if(result.ok){selectedTower=null;notify(`守護塔已出售，回收 ${result.refund} 文。`);}else notify(result.reason);sync();}
function updateSelection(){const focusId=document.activeElement?.id;const box=$('selection');const tower=game.towers.find(t=>t.id===selectedTower);if(tower){const spec=TYPES[tower.type],stats=towerStats(tower.type,tower.level),cost=upgradeCost(tower);box.innerHTML=`<p class="eyebrow">KEEPER / 據點 ${tower.padId.slice(1)}</p><h3>${spec.name} · ${'●'.repeat(tower.level)}${'○'.repeat(3-tower.level)}</h3><p>${spec.description}</p><div class="stats"><span>傷害 ${stats.damage}</span><span>射程 ${stats.range}</span><span>${stats.interval} 秒／次</span></div><div class="actions"><button id="upgrade" class="primary" ${cost===null||game.gold<cost||['won','lost'].includes(game.status)?'disabled':''}>${cost===null?'已達三級':`升級 ${cost} 文`}</button><button id="sell" ${['won','lost'].includes(game.status)?'disabled':''}>出售 +${sellValue(tower)} 文</button></div>`;$('upgrade').onclick=upgrade;$('sell').onclick=sell;}else if(buildType){const spec=TYPES[buildType],stats=towerStats(buildType);box.innerHTML=`<p class="eyebrow">PLACE YOUR KEEPER</p><h3>${spec.name} · ${spec.cost} 文</h3><p>${spec.description}</p><div class="stats"><span>傷害 ${stats.damage}</span><span>射程 ${stats.range}</span></div><button id="cancel-build" class="quiet">取消選塔</button>`;$('cancel-build').onclick=()=>{buildType=null;notify('已取消選塔，銅錢未扣除。');sync();};}else box.innerHTML='<p class="eyebrow">FIELD NOTES</p><h3>讓每一文錢，都照亮一段路。</h3><p>轉彎處能覆蓋更長的古道。茶香減速，再用鼓陣一次驅散成群霧靈。</p>';if(['upgrade','sell','cancel-build'].includes(focusId)&&$(focusId)&&!$(focusId).disabled)$(focusId).focus({preventScroll:true});}
let selectionSignature='';
function sync(){const ended=game.status==='won'||game.status==='lost';$('gold').textContent=game.gold;$('lives').textContent=game.lives;$('wave').textContent=game.status==='wave'?game.wave+1:game.wave;$('phase').textContent=ended?(game.status==='won'?'守夜成功':'燈火熄滅'):game.paused?'已暫停':game.status==='wave'?`霧靈 ${game.enemies.length} / 待現 ${game.spawnQueue.length}`:'整備中';$('start').disabled=game.status!=='build';$('start').innerHTML=game.status==='wave'?`第 ${game.wave+1} 夜進行中 <span>✦</span>`:ended?'守夜已結束':`迎接第 ${game.wave+1} 夜 <span>→</span>`;$('pause').textContent=game.paused?'繼續':'暫停';$('pause').disabled=ended;$('speed').textContent=`速度 ×${game.speed}`;$('pause-label').hidden=!game.paused||ended||$('guide').open||$('confirm').open;$('chapter').textContent=game.wave<4?'第一章 · 夜市初燈':game.wave<8?'第二章 · 茶田霧起':'第三章 · 山城守望';const wave=WAVES[Math.min(game.wave,11)];$('wave-title').textContent=ended?(game.status==='won'?'十二夜後，山城迎來破曉。':'整備塔陣，山城等你再來。'):`第 ${Math.min(game.wave+1,12)} 夜 · ${wave.name}`;$('wave-detail').textContent=ended?`本局驅散 ${game.kills} 隻霧靈 · 留住 ${game.lives} 盞燈。`:`${wave.description} ${wave.groups.map(g=>`${ENEMIES[g.type].name} ×${g.count}`).join(' · ')} · 守住補給 ${wave.reward} 文`;$('tip').textContent=wave.description;
for(const button of $('tower-shop').children){const type=button.dataset.type;button.classList.toggle('chosen',buildType===type);button.setAttribute('aria-pressed',String(buildType===type));button.disabled=ended;button.classList.toggle('unaffordable',game.gold<TYPES[type].cost);}
for(const button of $('pad-buttons').children){const tower=game.towers.find(t=>t.padId===button.dataset.pad);button.setAttribute('aria-label',`據點 ${button.dataset.pad.slice(1)}，${tower?`${TYPES[tower.type].name} ${tower.level} 級`:'空地'}`);button.disabled=ended;}
const signature=JSON.stringify([selectedTower,buildType,game.gold,game.status,game.towers.map(t=>[t.id,t.level])]);if(signature!==selectionSignature){selectionSignature=signature;updateSelection();}
$('result').hidden=!ended;if(ended){$('result-eyebrow').textContent=game.status==='won'?'THE VALLEY REMEMBERS':'A NEW NIGHT AWAITS';$('result-title').textContent=game.status==='won'?'萬燈破曉，山城無恙。':'霧深了，燈會再亮。';$('result-copy').textContent=game.status==='won'?`十二夜守望完成。你留下 ${game.lives} 盞燈，驅散 ${game.kills} 隻霧靈。謝謝你，替山城留了一條回家的路。`:`守到第 ${game.wave+1} 夜，驅散 ${game.kills} 隻霧靈。試著將天燈放在轉彎處，再用茶香配合鼓陣。`;$('retry').textContent=game.status==='won'?'再守十二夜 →':'重新佈陣 →';}}
$('start').onclick=()=>{const result=game.startWave();if(result.ok){music.cue('wave');notify(`第 ${game.wave+1} 夜：${WAVES[game.wave].name}。戰鬥中仍可建塔與升級。`);}else notify(result.reason);sync();};
function pause(){game.togglePause();music.setPaused(game.paused);sync();}
$('pause').onclick=pause;$('speed').onclick=()=>{game.setSpeed(game.speed===3?1:game.speed+1);sync();};
function openDialog(id){wasPaused=game.paused;if(!game.paused&&!['won','lost'].includes(game.status))game.togglePause();music.setPaused(true);$(id).showModal();sync();}
function closeDialog(id){$(id).close();if(!wasPaused&&game.paused)game.togglePause();music.setPaused(game.paused);sync();}
$('help').onclick=()=>openDialog('guide');$('close-guide').onclick=$('begin').onclick=()=>closeDialog('guide');$('restart').onclick=()=>openDialog('confirm');$('cancel-reset').onclick=()=>closeDialog('confirm');
function reset(){game.reset();selectedTower=null;buildType=null;hoverPad=null;oldWave=0;oldStatus='build';music.setPaused(false);last=performance.now();notify('新的一夜開始了。先選守護塔，再點 ＋ 據點。');sync();}
$('confirm-reset').onclick=()=>{$('confirm').close();reset();};$('retry').onclick=reset;
for(const id of ['guide','confirm'])$(id).addEventListener('cancel',event=>{event.preventDefault();closeDialog(id);});
$('sound').onclick=async()=>{const enabled=await music.toggle();$('sound').textContent=enabled?'♫ 音樂開':'♫ 音樂關';$('sound').setAttribute('aria-pressed',String(enabled));music.setPaused(game.paused);if(!enabled)notify('音樂已關閉；開啟時會播放原創合成樂曲。');};
window.addEventListener('keydown',event=>{if($('guide').open||$('confirm').open)return;if(event.code==='Space'&&!['BUTTON','INPUT','SELECT'].includes(document.activeElement.tagName)){event.preventDefault();pause();}if(event.key==='Escape'){buildType=null;selectedTower=null;notify('已取消選取，銅錢未扣除。');sync();}});
document.addEventListener('visibilitychange',()=>{if(document.hidden&&game.status==='wave'&&!game.paused){game.togglePause();music.setPaused(true);notify('離開畫面時已自動暫停，按繼續即可回到守夜。');sync();}last=performance.now();});
function frame(now){const dt=(now-last)/1000;last=now;game.update(dt);if(game.status!==oldStatus||game.wave!==oldWave){if(game.status==='build'&&game.wave>oldWave){music.cue('clear');notify(`第 ${game.wave} 夜守住了！補給 ${game.lastReward} 文。準備好再迎接下一夜。`);}if(['won','lost'].includes(game.status))music.cue(game.status);oldStatus=game.status;oldWave=game.wave;sync();}if(now-lastUI>120){sync();lastUI=now;}render(ctx,game,{selectedTower,selectedPad:null,hoverPad,buildType,reducedMotion});requestAnimationFrame(frame);}
sync();openDialog('guide');requestAnimationFrame(frame);
